### ISSUE TITLE
[Feature Request]: Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [4darsh-Dev/DecenTrade#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

### Use Case

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @myselfshivams 
go through contributing guidelines.

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @myselfshivams ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
