### ISSUE TITLE
[Feature Request]:  Add Contributor Page accessible from Footer

### ISSUE THREAD

**Issue by IkkiOcean** [4darsh-Dev/DecenTrade#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Description:**
To recognize and acknowledge the individuals who have contributed to this project, we need to implement a Contributor Page. This page will highlight the contributors and their respective roles and contributions, fostering community engagement.

**Tasks:**
1. **Create Contributor Page:**
   - Develop a layout for the Contributor Page that lists all contributors, including their names, roles, and brief descriptions of their contributions.
   - Implement the frontend components necessary to display the contributors' information effectively.

2. **Add Footer Link:**
   - Insert a link in the footer that directs users to the Contributor Page.
   - The footer link should be clearly labeled (e.g., "Contributors") for easy navigation.

### Demo

https://github.com/user-attachments/assets/3c250732-253e-4219-8b07-9bd6ebc22954

Note: This is demo and I will be using UI and context of DecenTrade for the page

### Use Case

1. **View Contributors:** Users can view a list of all contributors to understand who has contributed to the project.  
2. **Access Contributor Details:** Users can click on contributor names to view more information about their roles and contributions.  

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by IkkiOcean** [comment]
assign me under gssoc-ext

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
